### ISSUE TITLE
Sometimes returning incomplete data

### ISSUE THREAD

**Issue by kllindke** [cloudant/python-cloudant#373] opened 2018-04-19 19:06 UTC
Cloudant version affected: 2.7.0
Python version: 2.7.5
Sometimes get_attachment only returns a part of the attachment (not the full attachment) - require that method verifies full attachments received.

```python
client = cloudant.client.Cloudant(username, password, url=url, connect=True, adapter=Replay429Adapter(retries=20, initialBackoff=0.25))
myDocument = client[database][documentId]
allAttachments = myDocument['_attachments']
for attachment in allAttachments:
    print(len(myDocument.get_attachment(attachment)))
```

**Comment by smithsz** [comment] 2018-04-20 08:38
Unfortunately I've been unable to reproduce this bug. Can you please provide a simple script to show the failure?

Be aware that the database does compress attachments with certain MIME types. This may be causing the unexpected file sizes you're seeing.

**Comment by mikerhodes** [comment] 2018-04-20 09:53
Does this error happen when using something like [requests](http://docs.python-requests.org/en/master/) directly? It would be good to confirm whether this is `python-cloudant` or a problem with the underlying service.

**Comment by kllindke** [comment] 2018-04-20 11:26
It doesn’t result in a failure, it results in inconsistent attachment sizes
each call (for the same attachment). I’m sure it is an issue with the
underlying service, but it seems like it should be handled by cloudant and
result in an error or another call until the entire attachment is retrieved
or the max number of reconnections fails. I can’t provide the script
because it requires credentials but that print statement results in
different lengths being produced each call despite the fact that the
attachments haven’t changed at all. One run an attachment was around 400
bytes the next run it’s almost 1 MB.

**Comment by mikerhodes** [comment] 2018-04-23 10:49
Agreed it sounds like a pretty weird issue.

If it's most likely an issue with the service, please open a ticket via your Cloudant dashboard. That will give us a bit more context about your account so we can debug further on our side.

Please drop in the URL of this issue so we have the context here 😀 

Closing this issue.

**Closed by mikerhodes** 2018-04-23 10:49 UTC
Labels: bug
