### ISSUE TITLE
Remove redundant exists() check for client create_database call

### ISSUE THREAD

**Issue by alfinkel** [cloudant/python-cloudant#279] opened 2017-02-14 16:28 UTC
When using the client `create_database` method to create a database you are effectively making a call to the database `exists` method twice.  Once [here}(https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/client.py#L227) in `create_database` and then one more time [here](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/database.py#L340) in the database `create` method.

I propose that we fix this logic and remove the redundant call to `exists` by adding a keyword argument to the `create` method in CouchDatabase that would allow for turning on/off the "exists" check [here](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/database.py#L340).  The default would be for the check to be "on" so that no current behavior is affected.

I then propose fixing the logic [here](https://github.com/cloudant/python-cloudant/blob/master/src/cloudant/client.py#L226-L232) to utilize this new switch to turn off the redundant exists check in the `create_database` method of the CouchDB client class.

**Comment by ricellis** [comment] 2017-02-14 17:01
This is a duplicate of #142

**Closed by ricellis** 2017-02-14 17:01 UTC
