### ISSUE TITLE
cloudant/_common_util.py:22: DeprecationWarning: Using or importing the ABCs from 'collections'

### ISSUE THREAD

**Issue by olexandr-klymenko** [cloudant/python-cloudant#462] opened 2020-04-10 13:55 UTC
Please [read these guidelines](http://ibm.biz/cdt-issue-guide) before opening an issue.

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
1. Create a project with cloudant==2.12.0 as a dependency installed
2. Install pytest package.
3. Run test session

### 2. What you expected to happen
No warning messages during a test session

### 3. What actually happened
```
================================================================================ warnings summary ================================================================================
/home/oklymenko/.virtualenvs/zakaz-commerceman-api/lib/python3.8/site-packages/cloudant/_common_util.py:22
  /home/oklymenko/.virtualenvs/zakaz-commerceman-api/lib/python3.8/site-packages/cloudant/_common_util.py:22: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import Sequence

-- Docs: https://docs.pytest.org/en/latest/warnings.html

```

## Environment details
- Version(s) that are affected by this issue.
    == 2.12.0
- Python version
    == 3.8.1

**Comment by emlaver** [comment] 2020-04-10 14:04
@olexandr-klymenko thanks for finding this! We will add this to our backlog and get it done as soon as possible.

**Comment by ricellis** [comment] 2020-04-14 07:42
This is a duplicate of #451

**Closed by ricellis** 2020-04-14 07:42 UTC
Labels: duplicate
