### ISSUE TITLE
Replicator class should support new Cloudant and CouchDB 2.x replicator technology

### ISSUE THREAD

**Issue by pstatham** [cloudant/python-cloudant#347] opened 2018-01-02 23:10 UTC
The 2.7 Replicator::replication_state() and Replicator::follow_replication() methods (in https://github.com/cloudant/python-cloudant/blob/2.7.0/src/cloudant/replicator.py) use the CouchDB 1.x method of getting replication state and are not compatible with https://developer.ibm.com/dwblog/2017/replicator-apache-couchdb-cloudant/.

Can these be updated soon to work with the new replicator?

**Comment by ricellis** [comment] 2018-01-04 10:30
The existing (CouchDB 1.x) style state checks should work with newer versions of CouchDB by using the [`update_docs` setting](http://docs.couchdb.org/en/2.1.0/config/replicator.html#replicator/update_docs). This should be enabled for Cloudant clusters.

**Comment by pstatham** [comment] 2018-01-04 13:57
Good to know @ricellis. You say _"should be enabled for Cloudant clusters"_. How can my program confirm as a regular user (that can not access the `/_config` endpoint)?

**Comment by ricellis** [comment] 2018-01-04 15:09
What I meant by that "should" is that the option **is** enabled for Cloudant clusters so if you aren't getting replication doc updates for your Cloudant cluster then it isn't working as intended and you should contact support.

Based on that you shouldn't need to programmatically check that it is enabled, but if you wanted to check if it was working you could check for the `state` entries in the `_replicator` database document for your replication.

At some point (when all supported Cloudant versions have them) we'll change over to use the new APIs instead, but that will hopefully be transparent to caller's of `replication_state()` and `follow_replication()`.

**Comment by tomblench** [comment] 2018-05-23 08:43
Closing as PR has merged to master

**Closed by tomblench** 2018-05-23 08:43 UTC
Labels: enhancement
